// <auto-generated />
using System;
using DatabaseErstellen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseErstellen.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("DatabaseErstellen.Kurs", b =>
                {
                    b.Property<int>("KuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("StuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KuId");

                    b.ToTable("Kurse");
                });

            modelBuilder.Entity("DatabaseErstellen.Student", b =>
                {
                    b.Property<int>("StuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KursKuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .HasColumnType("TEXT");

                    b.HasKey("StuId");

                    b.HasIndex("KursKuId");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("DatabaseErstellen.Student", b =>
                {
                    b.HasOne("DatabaseErstellen.Kurs", null)
                        .WithMany("Studenten")
                        .HasForeignKey("KursKuId");
                });
#pragma warning restore 612, 618
        }
    }
}
